# -*- coding: utf-8 -*-
"""Контент личной страницы Ким Игоря на трёх языках.

Правки текста делаются здесь, потом `python3 scripts/build.py`.
Пустой href в списке = пункт не выводится на страницу.
"""

SITE = "https://kimigor.uz"
PHONE = "+998903239241"
PHONE_TEXT = "+998 90 323 92 41"
INSTAGRAM = "https://instagram.com/zvezdotank_"
LINKEDIN = "https://www.linkedin.com/in/zvezdotank/"
EMAIL = "zvezdotank@gmail.com"          # личная
EMAIL_WORK = "i.kim@wunder-digital.uz"  # корпоративная
AGENCY_URL = "https://wunder-digital.uz/"

# Для разметки Person: как Игоря ищут и в чём он разбирается.
ALT_NAMES = ["Igor Kim", "Ким Игорь Эдуардович", "Kim Igor", "Igor Kim Eduardovich"]
KNOWS = ["интернет-реклама", "контекстная реклама", "digital-маркетинг",
         "медийная реклама", "веб-аналитика", "performance-маркетинг",
         "online advertising", "digital marketing", "web analytics"]
FACEBOOK = ""  # профиль пока не добавлен — блок в контактах не выводится

TRACK_YEARS = list(range(2019, 2027))

# Карьера: годы общие, названия компаний не переводятся, роли и заметки — в каждом языке.
CAREER_YEARS = list(range(2007, 2027))
# Отрезки в долях года (2007.5 = июль 2007). Перекрытия по резюме обрезаны:
# на ленте видно основное место работы в каждый момент времени.
CAREER = [
    {"org": "Wunder Digital Uzbekistan", "from": 2018.7, "to": 2026.7, "key": True},
    {"org": "Whirl", "from": 2017.4, "to": 2018.7},
    {"org": "ЛЛК-Интернешнл", "from": 2011.4, "to": 2017.4, "key": True},
    {"org": "China Yuan Sheng", "from": 2010.75, "to": 2011.4},
    {"org": "Super iMax · EVO", "from": 2010.2, "to": 2010.75},
    {"org": "xxx-Astana", "from": 2009.85, "to": 2010.2},
    {"org": "Ural LM", "from": 2009.2, "to": 2009.7},
    {"org": "Abris Distribution", "from": 2008.6, "to": 2009.2},
    {"org": "StarMedia Ogilvy Uzbekistan", "from": 2007.5, "to": 2008.5, "key": True},
]


# Фотографии. Файлы общие, подписи переводятся в каждом языке ниже.
PHOTOS_WORK = ["rukopozhatie-konferenciya.jpeg",
               "yandex-conference-banner.jpeg",
               "yandex-conference-scena.jpeg"]

# Статусы агентства по платформам. Названия партнёрских программ не переводятся.
AGENCY = [
    {"platform": "Google", "items": [
        {"t": "Google Premier Partner", "y": "2023",
         "href": "https://marketing.uz/news/partners/wunder-digital-podtverdil-status-google-premier-partner-2025.htm"},
    ]},
    {"platform": "Yandex", "items": [
        {"t": "Yandex Certified Agency", "y": "2020", "href": ""},
        {"t": "Yandex Gold Partner", "y": "2024", "href": ""},
    ]},
    {"platform": "Meta", "items": [
        {"t": "Meta Certified Agency", "y": "",
         "href": "https://wunder-digital.uz/wunder-digital-prodlil-status-sertifitsirovannogo-agentstva-meta/"},
        {"t": "Meta Managed Agency", "y": "", "href": ""},
        {"t": "Meta Business Partner", "y": "", "href": ""},
    ]},
    {"platform": "Telegram", "items": [
        {"t": "Authorized Reseller", "y": "", "href": ""},
    ]},
]

# Обучение и сертификаты из резюме. Названия курсов не переводятся.
TRAINING = [
    {"y": 2007, "t": "Курс Михаила Дымшица", "o": "во время работы в StarMedia Ogilvy"},
    {"y": 2007, "t": "Маркетинговые решения", "o": "Кругозор, Алматы"},
    {"y": 2013, "t": "Технология выстраивания бизнес-контактов. Нетворкинг", "o": "MBS"},
    {"y": 2014, "t": "Ключевые клиенты всегда требуют максимум внимания", "o": "ЛЛК-Интернешнл"},
    {"y": 2014, "t": "Работа с VIP-клиентами. Сложности, тупики, решения", "o": "ЛЛК-Интернешнл"},
    {"y": 2015, "t": "Управление. Время. Клиенты и прибыль", "o": "ЛЛК-Интернешнл"},
    {"y": 2015, "t": "Ключевые клиенты от А до Я", "o": "ЛЛК-Интернешнл"},
    {"y": 2015, "t": "Продажи и маркетинг на рынке Узбекистана", "o": "ЛЛК-Интернешнл"},
    {"y": 2016, "t": "Планомерное преодоление барьеров. Управление временем", "o": "ЛЛК-Интернешнл"},
    {"y": 2016, "t": "5 стратегий увеличения продаж", "o": "Алишер Исаев, GreenLine Trading"},
    {"y": 2016, "t": "Business Triumph. Сопротивление продажам", "o": ""},
    {"y": 2016, "t": "Секреты успеха в жизни и бизнесе", "o": "Мурад Назаров"},
    {"y": 2016, "t": "Запуск новых продуктов на новых рынках", "o": "Школа современного бизнеса, Алматы"},
    {"y": 2017, "t": "Переговоры без поражений. Эффективные стратегии и тактики",
     "o": "Андрей Головачев, Москва"},
    {"y": 2018, "t": "Agile — гибкая методология разработки ПО", "o": "Whirl Ukraine"},
    {"y": 2018, "t": "Scrum — методология управления проектами", "o": "Whirl Ukraine"},
    {"y": 2018, "t": "Google Ads — основы", "o": "сертификат Google"},
    {"y": 2020, "t": "Google Ads — поисковые кампании", "o": "сертификат Google"},
    {"y": 2020, "t": "Яндекс.Метрика", "o": "сертификат Яндекса"},
    {"y": 2021, "t": "Яндекс аналитика", "o": "Яндекс"},
    {"y": 2022, "t": "Google аналитика", "o": "Google"},
    {"y": 2022, "t": "Поисковая реклама", "o": "Google"},
    {"y": 2023, "t": "Google Ads", "o": "Google"},
    {"y": 2023, "t": "DV360", "o": "Admixer Uzbekistan"},
    {"y": 2023, "t": "Фокус на подчинённом", "o": "IHCA, управленческие навыки"},
]

PHOTOS_TEAM = ["komanda-registan.jpeg", "komanda-ofis-1.jpeg", "komanda-vyezd.jpeg"]

LANGS = [
    ("ru", "RU", "/"),
    ("en", "EN", "/en/"),
    ("uz", "UZ", "/uz/"),
]

DATA = {
    "ru": {
        "htmlLang": "ru",
        "ogLocale": "ru_RU",
        "title": "Ким Игорь — digital-эксперт и интернет-реклама в Ташкенте | CEO Wunder Digital",
        "description": "Ким Игорь, Ташкент — CEO Wunder Digital Uzbekistan и председатель digital-комитета Маркетинговой ассоциации. 19 лет в продажах и маркетинге, 13 из них в интернет-рекламе и аналитике.",
        "kicker": "Digital-эксперт и интернет-реклама, Ташкент",
        "name": "Ким Игорь",
        "jobTitle": "CEO Wunder Digital Uzbekistan",
        "lede": "13 лет в digital-маркетинге, с 2019 года возглавляю Wunder Digital "
                "Uzbekistan. Занимаюсь digital- и AI-трансформацией маркетинга, работаю "
                "с Samsung, Beeline, Pepsi. Ниже — хронология, у каждой записи есть "
                "ссылка на источник.",
        "photoAlt": "Ким Игорь, Ташкент — CEO Wunder Digital Uzbekistan, эксперт по интернет-рекламе",
        "photoSlot": "Фото: marketing.uz",
        "skipLink": "К содержанию",
        "langLabel": "Язык страницы",
        "statuses": [
            "CEO Wunder Digital Uzbekistan",
            "Член правления Маркетинговой ассоциации Узбекистана",
            "Председатель digital-комитета Маркетинговой ассоциации Узбекистана",
            "Фокус: digital- и AI-трансформация маркетинга",
        ],
        "trackTitle": "Должности и статусы",
        "track": [
            {"label": "CEO Wunder Digital Uzbekistan", "from": 2019, "key": True},
            {"label": "Сертифицированное агентство Яндекса", "from": 2020},
            {"label": "Google Premier Partner", "from": 2023},
            {"label": "Член правления МАУ", "from": 2024},
            {"label": "Председатель digital-комитета МАУ", "from": 2024, "key": True},
            {"label": "Yandex Direct Gold Partner", "from": 2024, "key": True},
            {"label": "Meta Managed Partner", "from": 2025},
            {"label": "Meta Science Partner", "from": 2026, "key": True},
        ],
        "workTitle": "В работе",
        "work": [
            "Кулуары отраслевой конференции, Ташкент",
            "Yandex Ads Conference Uzbekistan",
            "Yandex Ads Conference Uzbekistan, участники на сцене",
        ],
        "teamTitle": "Команда",
        "team": [
            "Команда Wunder Digital, Самарканд",
            "Офис в Ташкенте",
            "Выездная встреча команды",
        ],
        "timelineTitle": "Хронология",
        "eraSales": "продажи и дистрибуция",
        "eraDigital": "digital",
        "milestones": [
            {"year": 2007, "text": "Первый опыт в рекламном бизнесе"},
            {"year": 2011, "text": "Первый сайт на WordPress, сертификация Google по рекламе и аналитике"},
            {"year": 2018, "text": "Открыл офис Wunder Digital в Ташкенте"},
            {"year": 2020, "text": "Сертифицированное агентство Яндекса", "co": True},
            {"year": 2023, "text": "Google Premier Partner", "co": True},
            {"year": 2025, "text": "Топ-35 маркетологов Узбекистана"},
            {"year": 2024, "text": "Член правления МАУ"},
            {"year": 2024, "text": "Председатель digital-комитета МАУ"},
            {"year": 2024, "text": "Yandex Direct Gold Partner", "co": True},
        ],
        "trainingTitle": "Обучение и сертификаты",
        "trainingNote": "курсов",
        "trainingHint": "обучений за год",
        "careerTitle": "Опыт работы",
        "careerNote": "19 лет, из них 13 в digital",
        "jobs": [
            {"role": "CEO", "when": "сентябрь 2018 — настоящее время",
             "note": "Открыл офис Wunder Digital в Узбекистане с нуля: регистрация, команда, "
                     "коммерческая стратегия, каналы продаж. В 2020 году агентство признано "
                     "№1 по контекстной рекламе и №1 в SEO в Узбекистане."},
            {"role": "Директор по продажам и маркетингу", "when": "июнь 2017 — сентябрь 2018",
             "note": "Монетизация публичных Wi-Fi-сетей. Провёл проект от идеи до монетизации, "
                     "защитил технико-экономическое обоснование перед национальным оператором, "
                     "подключил 40 партнёров по Ташкенту."},
            {"role": "Менеджер корпоративных продаж", "when": "июнь 2011 — июль 2018",
             "note": "Здесь начался путь в digital: изучил веб-разработку, рекламу Google и аналитику — "
                     "сделал сайт компании и сам настроил интернет-рекламу. Организовал сеть сбыта "
                     "с нуля, лучшие результаты по продажам за четыре года."},
            {"role": "Менеджер по проектам", "when": "октябрь 2010 — август 2014",
             "note": "Поставки промышленного оборудования от китайских заводов: пивоваренные "
                     "линии, прессовое оборудование, стройматериалы."},
            {"role": "Менеджер корпоративного отдела", "when": "март — сентябрь 2010",
             "note": "Интернет-провайдер на технологии WiMAX, корпоративный сегмент."},
            {"role": "Руководитель отдела продаж", "when": "ноябрь 2009 — март 2010",
             "note": "Новое направление компании в Астане: компьютерное оборудование и "
                     "системы видеонаблюдения, набор команды."},
            {"role": "Менеджер по продажам", "when": "март — сентябрь 2009",
             "note": "Компьютерное и периферийное оборудование, Xerox и Kyocera, Екатеринбург."},
            {"role": "Менеджер по продажам", "when": "август 2008 — апрель 2009",
             "note": "Дистрибуция ИТ и телекоммуникаций в СНГ."},
            {"role": "Менеджер по развитию бизнеса", "when": "июль 2007 — июнь 2008",
             "note": "Первая работа и знакомство с рекламным рынком — на него он вернётся "
                     "десять лет спустя. Форум IBM Innovation Day, запуск бренда Vogue Arome, "
                     "программа вакцинации по заказу UNICEF."},
        ],
        "personTitle": "Коротко",
        "person": [
            {"k": "Родился", "v": "24 сентября 1983 года"},
            {"k": "Живёт", "v": "Ташкент, Узбекистан"},
            {"k": "Образование", "v": "Ташкентский университет информационных технологий, "
                                      "телекоммуникации, бакалавр"},
            {"k": "Языки", "v": "русский — родной, английский — C1"},
            {"k": "Увлечения", "v": "digital, веб-продакшн, ИИ, фотография и видео"},
        ],
        "aboutTitle": "О себе",
        "rolesTitle": "Роли и должности",
        "awardsTitle": "Достижения и награды",
        "talksTitle": "Выступления",
        "juryTitle": "Жюри и судейство",
        "skillsTitle": "Инструменты и платформы",
        "mediaTitle": "Публикации в медиа",
        "pagesTitle": "Официальные страницы и анонсы",
        "navCareer": "Опыт",
        "navTraining": "Обучение",
        "trainingPageTitle": "Обучение, курсы и сертификаты",
        "allTraining": "Все курсы и сертификаты", "navSpeaking": "Выступления",
        "navJury": "Судейство", "navMedia": "Медиа",
        "careerPageTitle": "Опыт работы и должности",
        "speakingPageTitle": "Выступления на форумах и конференциях",
        "juryPageTitle": "Работа в жюри профессиональных конкурсов",
        "allCareer": "Весь опыт работы", "allSpeaking": "Все выступления",
        "allJury": "Всё судейство",
        "statusOn": "на связи", "statusOff": "не на связи",
        "statusLeft": "ещё", "statusBack": "буду через",
        "units": "д|ч|мин", "workHours": "пн–пт, 9:00–18:00, Ташкент",
        "mediaAll": "Все упоминания в медиа",
        "mediaPageTitle": "Публикации, комментарии и официальные страницы",
        "backHome": "На главную",
        "quotesTitle": "Отзывы",
        "contactKicker": "Контакты",
        "contactTitle": "Выступление, экспертиза, интервью",
        "phoneLabel": "Телефон",
        "emailWorkLabel": "Рабочая почта",
        "agencyLabel": "Агентство",
        "emailLabel": "Почта",
        "place": "Ташкент, Узбекистан",
        "unitEvents": "событий", "unitJury": "конкурсов",
        "unitMedia": "материалов", "unitPages": "ссылок",
        "about": [
            "CEO Wunder Digital Uzbekistan, эксперт в области digital-маркетинга. Более 13 лет "
            "в индустрии: эффективность рекламных инвестиций, performance-маркетинг, внедрение "
            "современных digital-решений.",
            "Возглавляет офис Wunder Digital в Узбекистане с момента основания и отвечает за "
            "стратегическое развитие компании на локальном рынке. До прихода в Wunder Digital "
            "занимал руководящие должности в крупных международных компаниях, где отвечал за "
            "digital-продвижение. Работает с крупнейшими рекламодателями рынка: Samsung, "
            "Beeline, Pepsi и др.",
            "Входит в топ-35 маркетологов Узбекистана, представляет Digital-комитет "
            "Маркетинговой ассоциации Узбекистана, выступает на форумах по digital-трансформации, "
            "аналитике и будущему рекламного рынка, работает в составе жюри профессиональных "
            "конкурсов.",
        ],
        "proof": "источник",
        "roles": [
            {"title": "CEO", "org": "Wunder Digital Uzbekistan", "period": "с 2019 года",
             "href": "https://marketing.uz/about/board/kim-igor.htm"},
            {"title": "Председатель digital-комитета", "org": "Маркетинговая ассоциация Узбекистана",
             "period": "с июля 2024",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
            {"title": "Топ-35 маркетологов Узбекистана", "org": "Маркетинговая ассоциация Узбекистана",
             "period": "по итогам 2025",
             "href": "https://marketing.uz/news/association/top35-marketologov-uzbekistana-po-itogam-2025-goda.htm"},
            {"title": "Член правления", "org": "Маркетинговая ассоциация Узбекистана",
             "period": "по настоящее время",
             "href": "https://marketing.uz/about/board/kim-igor.htm"},
            {"title": "Эксперт ассоциации", "org": "Маркетинговая ассоциация Узбекистана",
             "period": "по настоящее время",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
        ],
        "awards": [
            {"year": "2025", "title": "Топ-35 маркетологов Узбекистана",
             "desc": "Включён в список ведущих маркетологов страны по итогам года.",
             "href": "https://marketing.uz/news/association/top35-marketologov-uzbekistana-po-itogam-2025-goda.htm"},
            {"year": "с 2024", "title": "Председатель digital-комитета",
             "desc": "Маркетинговая ассоциация Узбекистана.",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
            {"year": "с 2024", "title": "Член правления",
             "desc": "Маркетинговая ассоциация Узбекистана.",
             "href": "https://marketing.uz/about/board/"},
            {"year": "—", "title": "Эксперт ассоциации",
             "desc": "Маркетинговая ассоциация Узбекистана.",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
        ],
        "agencyTitle": "Достижения агентства",
        "agencyNote": "Wunder Digital Uzbekistan под его руководством",
        "talks": [
            {"event": "Tashkent Advertising Festival TAF!26", "sub": "Спикер конференции",
             "meta": "Ташкент, Hyatt Regency, 2026", "href": "https://taf26.marketing.uz/speakers/24.htm"},
            {"event": "Tashkent Marketing Forum 2026", "sub": "Куратор digital-секции",
             "meta": "Ташкент, 14 февраля 2026",
             "href": "https://tmf26.marketing.uz/forum-curators/igor-kim.htm"},
            {"event": "Tashkent Marketing Forum 2025", "sub": "Секция Digital Marketing",
             "meta": "Ташкент, 2025",
             "href": "https://marketing.uz/news/association/cpikers-sektsii-digital-marketing-na-tashkent-marketing-forum-2025.htm"},
            {"event": "Tashkent Advertising Festival TAF!25",
             "sub": "Спикер секции Digital communications", "meta": "Ташкент, 11–12 октября 2025",
             "href": "https://uznews.uz/ru/news/103608"},
            {"event": "Yandex Ads Conference Uzbekistan",
             "sub": "«Зачем медийная реклама бизнесу и как сделать так, чтобы она приносила результат»",
             "meta": "Ташкент, Hilton Tashkent City, 14 мая 2024",
             "href": "https://yandex.ru/adv/project/yaconfuzb2024"},
            {"event": "Tashkent Digital Marketing Forum 2023", "sub": "Куратор форума",
             "meta": "Ташкент, 2023",
             "href": "https://marketing.uz/digital-forum/kuratory-foruma/igor-kim.htm"},
            {"event": "Big Data Day, Wunder Digital",
             "sub": "«Как увеличить продажи застройщика на 66%: первый кейс с использованием "
                    "Big Data мобильного оператора в Узбекистане»",
             "meta": "27 апреля 2023", "href": "https://tribune.kz/wunder-digital-agency-provedet-big-data-day/"},
            {"event": "Вебинар о продвижении недвижимости, Казахстан — Узбекистан — Беларусь",
             "sub": "«Как увеличить продажи застройщика на 66%: первый кейс с использованием "
                    "Big Data мобильного оператора в Узбекистане»",
             "meta": "30 мая 2023",
             "href": "https://dknews.kz/ru/biznes/290580-uspeshnaya-prodazha-nedvizhimosti-v-kazahstane-sovety"},
            {"event": "Конференция Яндекса в Узбекистане", "sub": "Спикер",
             "meta": "Ташкент, 9 декабря 2022", "href": "https://www.gazeta.uz/ru/2022/12/01/yandeks-ad/"},
        ],
        "jury": [
            {"event": "Brand Awards International 2026", "sub": "Член жюри", "meta": "2026",
             "href": "https://bai26.marketing.uz/en/judges/igor-kim.htm"},
            {"event": "Ташкентский фестиваль рекламы TAF!, конкурс", "sub": "Член жюри", "meta": "2024",
             "href": "https://tafkonkurs-2024.marketing.uz/judges/kim-igor.htm"},
            {"event": "Ташкентский фестиваль рекламы TAF!, конкурс", "sub": "Эксперт конкурса",
             "meta": "2023", "href": "https://marketing.uz/tafexpert-konkurs-2023"},
            {"event": "ePlus Award", "sub": "Член жюри", "meta": "2024",
             "href": "https://car.eplus.marketing/car/award/jury/jury-old/2024"},
            {"event": "ePlus Award", "sub": "Член жюри", "meta": "2023",
             "href": "https://car.eplus.marketing/car/award/jury/jury-old/2023/"},
            {"event": "Бренд года", "sub": "Член жюри", "meta": "2023",
             "href": "https://brendgoda-2023.marketing.uz/judges/kim-igor.htm"},
            {"event": "Бренд года", "sub": "Член жюри", "meta": "2022",
             "href": "https://marketing.uz/brend-goda-2022/jury/kim-igor.htm"},
        ],
        "skills": [
            {"group": "Реклама и закупка",
             "items": "Google Ads · Yandex Ads · Meta Ads · DV360 · Telegram Ads"},
            {"group": "Аналитика", "items": "Google Analytics · Yandex Metrica · AppMetrica"},
            {"group": "Мобильная атрибуция", "items": "Adjust · AppsFlyer"},
            {"group": "Веб-продакшн", "items": "WordPress · Tilda"},
        ],
        "media": [
            {"title": "Маркетинг как драйвер роста бизнеса: что обсудят на Tashkent Marketing Forum 2026",
             "outlet": "PR.uz, 04.02.2026", "href": "https://pr.uz/marketing-kak-drajver-rosta/"},
            {"title": "Как прошёл четвёртый международный Tashkent Marketing Forum 2026",
             "outlet": "WeProject Media, 2026",
             "href": "https://weproject.media/articles/detail/kak-proshel-chetvertyy-mezhdunarodnyy-tashkent-marketing-forum-2026/"},
            {"title": "Как маркетинг должен развивать бизнес и кто покажет, как это делать в 2026 году",
             "outlet": "Gazeta.uz, 04.02.2026", "href": "https://www.gazeta.uz/ru/2026/02/04/marketing-forum-2026/"},
            {"title": "Как маркетинг должен развивать бизнес и кто покажет, как это делать в 2026 году",
             "outlet": "Nuz.uz, 27.01.2026",
             "href": "https://nuz.uz/2026/01/27/kak-marketing-dolzhen-razvivat-biznes-i-kto-pokazhet-kak-eto-delat-v-2026-godu/"},
            {"title": "Как маркетинг должен развивать бизнес — и кто покажет, как это делать в 2026 году",
             "outlet": "Vzglyad.uz, 23.01.2026",
             "href": "https://vzglyad.uz/2026/01/23/kak-marketing-dolzhen-razvivat-biznes-i-kto-pokazhet-kak-eto-delat-v-2026-godu/"},
            {"title": "Профиль эксперта и колумниста издания", "outlet": "Kursiv Media Узбекистан",
             "href": "https://uz.kursiv.media/expert/igor-kim/"},
            {"title": "От экрана к покупателю: что такое цифровая наружная реклама и как она помогает "
                      "отслеживать доходимость до точек продаж — авторская колонка",
             "outlet": "Kursiv Media Узбекистан, 21.07.2025",
             "href": "https://uz.kursiv.media/opinions/ot-ekrana-k-pokupatelyu-chto-takoe-czifrovaya-naruzhnaya-reklama-i-kak-ona-pomogaet-otslezhivat-dohodimost-do-tochek-prodazh/"},
            {"title": "Седьмой Ташкентский международный фестиваль рекламы TAF!25 объявил победителей "
                      "и подвёл итоги", "outlet": "Nova24.uz, 2025",
             "href": "https://nova24.uz/uzbekistan/sedmoj-tashkentskij-mezhdunarodnyj-festival-reklamy-taf-25-obyavil-pobeditelej-i-podvel-itogi/"},
            {"title": "Международная рекламная конференция TAF!25: возможность выйти на новый уровень "
                      "в рекламе вашего бизнеса", "outlet": "Frank.uz, 2025",
             "href": "https://frank.uz/news/mezhdunarodnaya-reklamnaya-konferencziya-taf25-vozmozhnost-vyjti-na-novyj-uroven-v-reklame-vashego-biznesa/"},
            {"title": "Диджитал-маркетинг в Узбекистане: тенденции 2025 года. Экспертный комментарий",
             "outlet": "Astana Hub, 2025",
             "href": "https://astanahub.com/en/blog/didzhital-marketing-v-uzbekistane-tendentsii-2025-goda1759934363"},
            {"title": "Digital-маркетинг в Узбекистане: ключевые тренды 2025 года. Экспертный комментарий",
             "outlet": "Sostav.ru, 08.10.2025", "href": "https://www.sostav.ru/blogs/141843/68775"},
            {"title": "Диджитал-маркетинг в Узбекистане — тенденции 2025 года. Экспертный комментарий",
             "outlet": "BYYD, 07.10.2025",
             "href": "https://www.byyd.me/ru/blog/2025/10/digital-marketing-in-uzbekistan-trends-for-2025/"},
            {"title": "Завершилось формирование судейского корпуса E+ Awards Центральная Азия 2024",
             "outlet": "Tribune.kz, 2024",
             "href": "https://tribune.kz/zavershilos-formirovanie-sudejskogo-korpusa-e-awards-tsentralnaya-aziya-2024/"},
            {"title": "Как продвигать недвижимость, чтобы её покупали? Вебинар Wunder Digital",
             "outlet": "Spot.uz, 25.05.2023", "href": "https://www.spot.uz/ru/2023/05/25/wunder-digital/"},
            {"title": "Как продвигать недвижимость, чтобы её покупали? Бесплатный вебинар от Wunder Digital",
             "outlet": "Goodstart.by, 2023",
             "href": "https://goodstart.by/new/wunder-digital-webinar-promotion-realty-2023"},
            {"title": "Как продвигать недвижимость, чтобы её покупали? Бесплатный вебинар от Wunder Digital",
             "outlet": "Domovita.by, 2023",
             "href": "https://domovita.by/news/kak-prodvigat-nedvizimost-ctoby-ee-pokupali-besplatnyj-vebinar-ot-wunder-digital"},
            {"title": "Как продвигать недвижимость, чтобы её покупали? Бесплатный вебинар от Wunder Digital",
             "outlet": "Homsters.kz, 2023",
             "href": "https://info.homsters.kz/kak-prodvigat-nedvizhimost-chtoby-ee-pokupali-besplatnyj-vebinar-ot-wunder-digital/"},
            {"title": "Как продвигать недвижимость, чтобы её покупали? Вебинар Wunder Digital — "
                      "анонс с программой", "outlet": "«Экономическая газета» (neg.by), 31.05.2023",
             "href": "https://neg.by/novosti/otkrytj/kak-prodvigat-nedvizhimost-chtoby-ee-pokupali-besplatnyy-vebinar-ot-wunder-digital/"},
            {"title": "В Узбекистане стартовал первый Tashkent Digital Marketing Forum",
             "outlet": "PC.uz, 2023", "href": "https://pc.uz/news/152339-v-uzbekistane-startoval-pervyj"},
            {"title": "В Ташкенте прошёл первый международный Tashkent Digital Marketing Forum 2023",
             "outlet": "UzDaily, 2023",
             "href": "https://www.uzdaily.uz/ru/v-tashkente-proshel-pervyi-mezhdunarodnyi-tashkent-digital-marketing-forum-2023/"},
            {"title": "3 тренда в рекламе лекарственных средств в 2023 году в Узбекистане",
             "outlet": "Wunder Digital, 2023",
             "href": "https://wunder-digital.uz/3-trenda-v-reklame-lekarstvennyh-sredstv-v-2023-godu-v-uzbekistane/"},
            {"title": "Wunder Digital Agency приглашает на Big Data Day — анонс с программой",
             "outlet": "Edu-afisha, 2023",
             "href": "https://edu-afisha.ru/event/wunder-digital-agency-priglashaet-na-big-data-day/"},
            {"title": "Материал о маркетинге и PR", "outlet": "Spot.uz, 06.12.2022",
             "href": "https://www.spot.uz/ru/2022/12/06/marketing-pr/"},
            {"title": "Конференция Яндекса в Узбекистане: анонс с программой и спикерами",
             "outlet": "Spot.uz, 01.12.2022", "href": "https://www.spot.uz/ru/2022/12/01/yandeks-ad/"},
            {"title": "Ребрендинг Wunder: как это происходило и что об этом думают CEO офисов "
                      "в Казахстане и Узбекистане", "outlet": "Tribune.kz",
             "href": "https://tribune.kz/rebrending-wunder-kak-eto-proishodilo-i-chto-ob-etom-dumayut-ceo-ofisov-v-kazahstane-i-uzbekistane/"},
        ],
        "pages": [
            {"title": "Brand Awards International 2026 — сайт премии",
             "outlet": "Маркетинговая ассоциация Узбекистана, 2026", "href": "https://bai26.marketing.uz/"},
            {"title": "Правление Маркетинговой ассоциации Узбекистана — состав",
             "outlet": "Маркетинговая ассоциация Узбекистана", "href": "https://marketing.uz/about/board/"},
            {"title": "Знакомьтесь с кураторами Tashkent Marketing Forum 2026",
             "outlet": "Маркетинговая ассоциация Узбекистана, 2026",
             "href": "https://marketing.uz/news/association/-znakomtes-s-kuratorami-tashkent-marketing-forum-2026.htm"},
            {"title": "Tashkent Marketing Forum 2025 — сайт форума",
             "outlet": "Маркетинговая ассоциация Узбекистана, 2025", "href": "https://tmf25.marketing.uz/"},
            {"title": "Международная рекламная конференция TAF!25: возможность выйти на новый уровень "
                      "в рекламе вашего бизнеса", "outlet": "Маркетинговая ассоциация Узбекистана, 2025",
             "href": "https://marketing.uz/news/association/mezhdunarodnaya-reklamnaya-konferentsiya-taf25-vozmozhnost-vyjti-na-novyj-uroven-v-reklame-vashego-biznesa.htm"},
            {"title": "Спикеры секции Digital communications на TAF!25",
             "outlet": "Маркетинговая ассоциация Узбекистана, 2025",
             "href": "https://marketing.uz/news/association/predstavlyaem-spikerov-sektsii-digital-communications-na-tashkentskom-mezhdunarodnom-festivale-reklamy-taf25.htm"},
            {"title": "Конкурс TAF! 2024 — сайт конкурса",
             "outlet": "Маркетинговая ассоциация Узбекистана, 2024", "href": "https://tafkonkurs-2024.marketing.uz/"},
            {"title": "Анонс Yandex Ad Conference в Ташкенте, 9 декабря",
             "outlet": "Facebook, Wunder Digital UZ, 2022",
             "href": "https://www.facebook.com/WunderDigitalUZ/posts/2724650761004617/"},
            {"title": "Yandex Ads Conference Uzbekistan — страница события с программой",
             "outlet": "Яндекс, 2022", "href": "https://yandex.ru/promo/events/yaconfuz"},
            {"title": "Заседание правления Маркетинговой ассоциации Узбекистана в новом составе, 9 июля",
             "outlet": "Маркетинговая ассоциация Узбекистана",
             "href": "https://marketing.uz/news/association/9-iyulya-sostoyalos-zasedanie-pravleniya-marketingovoj-assotsiatsii-uzbekistana-v-novom-sostave-.htm"},
            {"title": "Tashkent Digital Marketing Forum — страница форума",
             "outlet": "Маркетинговая ассоциация Узбекистана", "href": "https://marketing.uz/digital-forum/"},
            {"title": "Ритейл-маркетинг: как соединить продажи и узнаваемость в одной стратегии",
             "outlet": "Маркетинговая ассоциация Узбекистана",
             "href": "https://marketing.uz/news/association/ritejl-marketing-kak-soedinit-prodazhi-i-uznavaemost-v-odnoj-strategii.htm"},
            {"title": "В Узбекистане выберут Digital-инноватора года",
             "outlet": "Маркетинговая ассоциация Узбекистана",
             "href": "https://marketing.uz/news/partners/v-uzbekistane-vyberut-digital-innovatora-goda.htm"},
        ],
        # Пусто — секция «Отзывы» не выводится, пока не появятся реальные цитаты.
        "quotes": [],
    },

    "en": {
        "htmlLang": "en",
        "ogLocale": "en_US",
        "title": "Igor Kim — digital marketing and online advertising in Tashkent | Wunder Digital CEO",
        "description": "Igor Kim, Tashkent — CEO of Wunder Digital Uzbekistan and chairman of the digital committee at the Marketing Association. 19 years in sales and marketing, 13 of them in online advertising and analytics.",
        "kicker": "Digital expert and online advertising, Tashkent",
        "name": "Igor Kim",
        "jobTitle": "CEO of Wunder Digital Uzbekistan",
        "lede": "13 years in digital marketing, leading Wunder Digital Uzbekistan since "
                "2019. Focused on digital and AI transformation of marketing, working "
                "with Samsung, Beeline, Pepsi. Below is a timeline; every entry has "
                "a link to its source.",
        "photoAlt": "Igor Kim, Tashkent — CEO of Wunder Digital Uzbekistan, online advertising expert",
        "photoSlot": "Photo: marketing.uz",
        "skipLink": "Skip to content",
        "langLabel": "Page language",
        "statuses": [
            "CEO of Wunder Digital Uzbekistan",
            "Board member, Marketing Association of Uzbekistan",
            "Chairman of the digital committee, Marketing Association of Uzbekistan",
            "Focus: digital and AI transformation of marketing",
        ],
        "trackTitle": "Roles and statuses",
        "track": [
            {"label": "CEO of Wunder Digital Uzbekistan", "from": 2019, "key": True},
            {"label": "Yandex certified agency", "from": 2020},
            {"label": "Google Premier Partner", "from": 2023},
            {"label": "Board member, MAU", "from": 2024},
            {"label": "Chairman of the digital committee, MAU", "from": 2024, "key": True},
            {"label": "Yandex Direct Gold Partner", "from": 2024, "key": True},
            {"label": "Meta Managed Partner", "from": 2025},
            {"label": "Meta Science Partner", "from": 2026, "key": True},
        ],
        "workTitle": "At work",
        "work": [
            "Industry conference, Tashkent",
            "Yandex Ads Conference Uzbekistan",
            "Yandex Ads Conference Uzbekistan, participants on stage",
        ],
        "teamTitle": "Team",
        "team": [
            "The Wunder Digital team, Samarkand",
            "The Tashkent office",
            "Team offsite",
        ],
        "timelineTitle": "Timeline",
        "eraSales": "sales and distribution",
        "eraDigital": "digital",
        "milestones": [
            {"year": 2007, "text": "First experience in the advertising business"},
            {"year": 2011, "text": "First WordPress site, Google certification in ads and analytics"},
            {"year": 2018, "text": "Opened the Wunder Digital office in Tashkent"},
            {"year": 2020, "text": "Yandex certified agency", "co": True},
            {"year": 2023, "text": "Google Premier Partner", "co": True},
            {"year": 2025, "text": "Top 35 marketers in Uzbekistan"},
            {"year": 2024, "text": "Board member, MAU"},
            {"year": 2024, "text": "Chairman of the digital committee, MAU"},
            {"year": 2024, "text": "Yandex Direct Gold Partner", "co": True},
        ],
        "trainingTitle": "Training and certificates",
        "trainingNote": "courses",
        "trainingHint": "courses this year",
        "careerTitle": "Experience",
        "careerNote": "19 years, 13 of them in digital",
        "jobs": [
            {"role": "CEO", "when": "September 2018 — present",
             "note": "Opened the Wunder Digital office in Uzbekistan from scratch: registration, "
                     "team, commercial strategy, sales channels. In 2020 the agency was named "
                     "the country’s No. 1 in paid search and No. 1 in SEO."},
            {"role": "Sales and marketing director", "when": "June 2017 — September 2018",
             "note": "Monetisation of public Wi-Fi networks. Ran the project from idea to revenue, "
                     "defended the feasibility study before the national operator and signed "
                     "40 partners across Tashkent."},
            {"role": "Corporate sales manager", "when": "June 2011 — July 2018",
             "note": "Where the digital path began: learned web development, Google Ads and analytics — "
                     "built the company website and ran the advertising himself. Created the "
                     "distribution network from scratch; best sales results in four years."},
            {"role": "Project manager", "when": "October 2010 — August 2014",
             "note": "Industrial equipment from Chinese plants: brewing lines, press equipment, "
                     "construction materials."},
            {"role": "Corporate sales manager", "when": "March — September 2010",
             "note": "WiMAX internet provider, corporate segment."},
            {"role": "Head of sales", "when": "November 2009 — March 2010",
             "note": "A new business line in Astana: computer equipment and video surveillance "
                     "systems, hiring the team."},
            {"role": "Sales manager", "when": "March — September 2009",
             "note": "Computer and peripheral equipment, Xerox and Kyocera, Yekaterinburg."},
            {"role": "Sales manager", "when": "August 2008 — April 2009",
             "note": "IT and telecom distribution across the CIS."},
            {"role": "Business development manager", "when": "July 2007 — June 2008",
             "note": "First job and first contact with the advertising market — he would return "
                     "to it ten years later. IBM Innovation Day forum, the Vogue Arome brand "
                     "launch, a UNICEF vaccination campaign."},
        ],
        "personTitle": "In brief",
        "person": [
            {"k": "Born", "v": "24 September 1983"},
            {"k": "Lives in", "v": "Tashkent, Uzbekistan"},
            {"k": "Education", "v": "Tashkent University of Information Technologies, "
                                    "telecommunications, BSc"},
            {"k": "Languages", "v": "Russian — native, English — C1"},
            {"k": "Interests", "v": "digital, web production, AI, photography and video"},
        ],
        "aboutTitle": "About",
        "rolesTitle": "Roles",
        "awardsTitle": "Recognition",
        "talksTitle": "Speaking",
        "juryTitle": "Jury work",
        "skillsTitle": "Tools and platforms",
        "mediaTitle": "In the media",
        "pagesTitle": "Official pages and announcements",
        "navCareer": "Experience",
        "navTraining": "Training",
        "trainingPageTitle": "Training, courses and certificates",
        "allTraining": "All courses and certificates", "navSpeaking": "Speaking",
        "navJury": "Jury", "navMedia": "Media",
        "careerPageTitle": "Experience and roles",
        "speakingPageTitle": "Talks at forums and conferences",
        "juryPageTitle": "Jury work at professional awards",
        "allCareer": "Full work history", "allSpeaking": "All talks",
        "allJury": "All jury work",
        "statusOn": "available", "statusOff": "offline",
        "statusLeft": "for another", "statusBack": "back in",
        "units": "d|h|min", "workHours": "Mon–Fri, 9:00–18:00, Tashkent",
        "mediaAll": "All media mentions",
        "mediaPageTitle": "Articles, commentary and official pages",
        "backHome": "Back to the main page",
        "quotesTitle": "References",
        "contactKicker": "Contact",
        "contactTitle": "Speaking, expertise, interviews",
        "phoneLabel": "Phone",
        "emailWorkLabel": "Work email",
        "agencyLabel": "Agency",
        "emailLabel": "Email",
        "place": "Tashkent, Uzbekistan",
        "unitEvents": "events", "unitJury": "awards",
        "unitMedia": "items", "unitPages": "links",
        "about": [
            "CEO of Wunder Digital Uzbekistan and a digital marketing expert with more than 13 years "
            "in the industry: advertising investment efficiency, performance marketing and the "
            "adoption of modern digital solutions.",
            "He has led the Wunder Digital office in Uzbekistan since it was founded and is "
            "responsible for the company’s strategic development on the local market. Before joining "
            "Wunder Digital he held leadership roles at large international companies, responsible "
            "for digital promotion. He works with the market’s biggest advertisers: Samsung, "
            "Beeline, Pepsi and others.",
            "Listed among the top 35 marketers in Uzbekistan, he represents the digital committee of "
            "the Marketing Association of Uzbekistan, speaks at forums on digital transformation, "
            "analytics and the future of advertising, and serves on juries of professional awards.",
        ],
        "proof": "source",
        "roles": [
            {"title": "CEO", "org": "Wunder Digital Uzbekistan", "period": "since 2019",
             "href": "https://marketing.uz/about/board/kim-igor.htm"},
            {"title": "Chairman, digital committee", "org": "Marketing Association of Uzbekistan",
             "period": "since July 2024",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
            {"title": "Top 35 marketers in Uzbekistan", "org": "Marketing Association of Uzbekistan",
             "period": "2025 ranking",
             "href": "https://marketing.uz/news/association/top35-marketologov-uzbekistana-po-itogam-2025-goda.htm"},
            {"title": "Board member", "org": "Marketing Association of Uzbekistan", "period": "present",
             "href": "https://marketing.uz/about/board/kim-igor.htm"},
            {"title": "Association expert", "org": "Marketing Association of Uzbekistan",
             "period": "present",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
        ],
        "awards": [
            {"year": "2025", "title": "Top 35 marketers in Uzbekistan",
             "desc": "Listed among the country’s leading marketers for the year.",
             "href": "https://marketing.uz/news/association/top35-marketologov-uzbekistana-po-itogam-2025-goda.htm"},
            {"year": "since 2024", "title": "Chairman of the digital committee",
             "desc": "Marketing Association of Uzbekistan.",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
            {"year": "since 2024", "title": "Board member",
             "desc": "Marketing Association of Uzbekistan.",
             "href": "https://marketing.uz/about/board/"},
            {"year": "—", "title": "Association expert",
             "desc": "Marketing Association of Uzbekistan.",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
        ],
        "agencyTitle": "Agency achievements",
        "agencyNote": "Wunder Digital Uzbekistan under his leadership",
        "talks": [
            {"event": "Tashkent Advertising Festival TAF!26", "sub": "Conference speaker",
             "meta": "Tashkent, Hyatt Regency, 2026", "href": "https://taf26.marketing.uz/speakers/24.htm"},
            {"event": "Tashkent Marketing Forum 2026", "sub": "Curator of the digital track",
             "meta": "Tashkent, 14 February 2026",
             "href": "https://tmf26.marketing.uz/forum-curators/igor-kim.htm"},
            {"event": "Tashkent Marketing Forum 2025", "sub": "Digital Marketing track",
             "meta": "Tashkent, 2025",
             "href": "https://marketing.uz/news/association/cpikers-sektsii-digital-marketing-na-tashkent-marketing-forum-2025.htm"},
            {"event": "Tashkent Advertising Festival TAF!25",
             "sub": "Speaker, Digital communications track", "meta": "Tashkent, 11–12 October 2025",
             "href": "https://uznews.uz/ru/news/103608"},
            {"event": "Yandex Ads Conference Uzbekistan",
             "sub": "“Why business needs display advertising and how to make it deliver”",
             "meta": "Tashkent, Hilton Tashkent City, 14 May 2024",
             "href": "https://yandex.ru/adv/project/yaconfuzb2024"},
            {"event": "Tashkent Digital Marketing Forum 2023", "sub": "Forum curator",
             "meta": "Tashkent, 2023",
             "href": "https://marketing.uz/digital-forum/kuratory-foruma/igor-kim.htm"},
            {"event": "Big Data Day, Wunder Digital",
             "sub": "“Growing a developer’s sales by 66%: the first case using mobile-operator "
                    "Big Data in Uzbekistan”",
             "meta": "27 April 2023", "href": "https://tribune.kz/wunder-digital-agency-provedet-big-data-day/"},
            {"event": "Webinar on real-estate marketing (KZ — UZ — BY)",
             "sub": "“Growing a developer’s sales by 66%: the first case using mobile-operator "
                    "Big Data in Uzbekistan”",
             "meta": "30 May 2023",
             "href": "https://dknews.kz/ru/biznes/290580-uspeshnaya-prodazha-nedvizhimosti-v-kazahstane-sovety"},
            {"event": "Yandex conference in Uzbekistan", "sub": "Speaker",
             "meta": "Tashkent, 9 December 2022", "href": "https://www.gazeta.uz/ru/2022/12/01/yandeks-ad/"},
        ],
        "jury": [
            {"event": "Brand Awards International 2026", "sub": "Jury member", "meta": "2026",
             "href": "https://bai26.marketing.uz/en/judges/igor-kim.htm"},
            {"event": "Tashkent Advertising Festival TAF! competition", "sub": "Jury member",
             "meta": "2024", "href": "https://tafkonkurs-2024.marketing.uz/judges/kim-igor.htm"},
            {"event": "Tashkent Advertising Festival TAF! competition", "sub": "Competition expert",
             "meta": "2023", "href": "https://marketing.uz/tafexpert-konkurs-2023"},
            {"event": "ePlus Award", "sub": "Jury member", "meta": "2024",
             "href": "https://car.eplus.marketing/car/award/jury/jury-old/2024"},
            {"event": "ePlus Award", "sub": "Jury member", "meta": "2023",
             "href": "https://car.eplus.marketing/car/award/jury/jury-old/2023/"},
            {"event": "Brand of the Year", "sub": "Jury member", "meta": "2023",
             "href": "https://brendgoda-2023.marketing.uz/judges/kim-igor.htm"},
            {"event": "Brand of the Year", "sub": "Jury member", "meta": "2022",
             "href": "https://marketing.uz/brend-goda-2022/jury/kim-igor.htm"},
        ],
        "skills": [
            {"group": "Advertising and buying",
             "items": "Google Ads · Yandex Ads · Meta Ads · DV360 · Telegram Ads"},
            {"group": "Analytics", "items": "Google Analytics · Yandex Metrica · AppMetrica"},
            {"group": "Mobile attribution", "items": "Adjust · AppsFlyer"},
            {"group": "Web production", "items": "WordPress · Tilda"},
        ],
        "media": [
            {"title": "Marketing as a growth driver: what Tashkent Marketing Forum 2026 will discuss",
             "outlet": "PR.uz, 04.02.2026", "href": "https://pr.uz/marketing-kak-drajver-rosta/"},
            {"title": "How the fourth international Tashkent Marketing Forum 2026 went",
             "outlet": "WeProject Media, 2026",
             "href": "https://weproject.media/articles/detail/kak-proshel-chetvertyy-mezhdunarodnyy-tashkent-marketing-forum-2026/"},
            {"title": "How marketing should grow a business and who will show how in 2026",
             "outlet": "Gazeta.uz, 04.02.2026", "href": "https://www.gazeta.uz/ru/2026/02/04/marketing-forum-2026/"},
            {"title": "How marketing should grow a business and who will show how in 2026",
             "outlet": "Nuz.uz, 27.01.2026",
             "href": "https://nuz.uz/2026/01/27/kak-marketing-dolzhen-razvivat-biznes-i-kto-pokazhet-kak-eto-delat-v-2026-godu/"},
            {"title": "How marketing should grow a business — and who will show how in 2026",
             "outlet": "Vzglyad.uz, 23.01.2026",
             "href": "https://vzglyad.uz/2026/01/23/kak-marketing-dolzhen-razvivat-biznes-i-kto-pokazhet-kak-eto-delat-v-2026-godu/"},
            {"title": "Contributing expert and columnist profile", "outlet": "Kursiv Media Uzbekistan",
             "href": "https://uz.kursiv.media/expert/igor-kim/"},
            {"title": "From screen to shopper: what DOOH is and how it tracks store visits — "
                      "author’s column", "outlet": "Kursiv Media Uzbekistan, 21.07.2025",
             "href": "https://uz.kursiv.media/opinions/ot-ekrana-k-pokupatelyu-chto-takoe-czifrovaya-naruzhnaya-reklama-i-kak-ona-pomogaet-otslezhivat-dohodimost-do-tochek-prodazh/"},
            {"title": "The seventh Tashkent international advertising festival TAF!25 announced "
                      "its winners", "outlet": "Nova24.uz, 2025",
             "href": "https://nova24.uz/uzbekistan/sedmoj-tashkentskij-mezhdunarodnyj-festival-reklamy-taf-25-obyavil-pobeditelej-i-podvel-itogi/"},
            {"title": "TAF!25 international advertising conference: a new level for your business",
             "outlet": "Frank.uz, 2025",
             "href": "https://frank.uz/news/mezhdunarodnaya-reklamnaya-konferencziya-taf25-vozmozhnost-vyjti-na-novyj-uroven-v-reklame-vashego-biznesa/"},
            {"title": "Digital marketing in Uzbekistan: 2025 trends. Expert commentary",
             "outlet": "Astana Hub, 2025",
             "href": "https://astanahub.com/en/blog/didzhital-marketing-v-uzbekistane-tendentsii-2025-goda1759934363"},
            {"title": "Digital marketing in Uzbekistan: key 2025 trends. Expert commentary",
             "outlet": "Sostav.ru, 08.10.2025", "href": "https://www.sostav.ru/blogs/141843/68775"},
            {"title": "Digital marketing in Uzbekistan — 2025 trends. Expert commentary",
             "outlet": "BYYD, 07.10.2025",
             "href": "https://www.byyd.me/ru/blog/2025/10/digital-marketing-in-uzbekistan-trends-for-2025/"},
            {"title": "The E+ Awards Central Asia 2024 jury line-up announced", "outlet": "Tribune.kz, 2024",
             "href": "https://tribune.kz/zavershilos-formirovanie-sudejskogo-korpusa-e-awards-tsentralnaya-aziya-2024/"},
            {"title": "How to market real estate so it sells: Wunder Digital webinar",
             "outlet": "Spot.uz, 25.05.2023", "href": "https://www.spot.uz/ru/2023/05/25/wunder-digital/"},
            {"title": "How to market real estate so it sells: free Wunder Digital webinar",
             "outlet": "Goodstart.by, 2023",
             "href": "https://goodstart.by/new/wunder-digital-webinar-promotion-realty-2023"},
            {"title": "How to market real estate so it sells: free Wunder Digital webinar",
             "outlet": "Domovita.by, 2023",
             "href": "https://domovita.by/news/kak-prodvigat-nedvizimost-ctoby-ee-pokupali-besplatnyj-vebinar-ot-wunder-digital"},
            {"title": "How to market real estate so it sells: free Wunder Digital webinar",
             "outlet": "Homsters.kz, 2023",
             "href": "https://info.homsters.kz/kak-prodvigat-nedvizhimost-chtoby-ee-pokupali-besplatnyj-vebinar-ot-wunder-digital/"},
            {"title": "How to market real estate so it sells: Wunder Digital webinar programme",
             "outlet": "Ekonomicheskaya Gazeta (neg.by), 31.05.2023",
             "href": "https://neg.by/novosti/otkrytj/kak-prodvigat-nedvizhimost-chtoby-ee-pokupali-besplatnyy-vebinar-ot-wunder-digital/"},
            {"title": "Uzbekistan’s first Tashkent Digital Marketing Forum opened", "outlet": "PC.uz, 2023",
             "href": "https://pc.uz/news/152339-v-uzbekistane-startoval-pervyj"},
            {"title": "Tashkent hosted the first international Tashkent Digital Marketing Forum 2023",
             "outlet": "UzDaily, 2023",
             "href": "https://www.uzdaily.uz/ru/v-tashkente-proshel-pervyi-mezhdunarodnyi-tashkent-digital-marketing-forum-2023/"},
            {"title": "Three trends in pharma advertising in Uzbekistan in 2023",
             "outlet": "Wunder Digital, 2023",
             "href": "https://wunder-digital.uz/3-trenda-v-reklame-lekarstvennyh-sredstv-v-2023-godu-v-uzbekistane/"},
            {"title": "Wunder Digital Agency invites to Big Data Day — programme",
             "outlet": "Edu-afisha, 2023",
             "href": "https://edu-afisha.ru/event/wunder-digital-agency-priglashaet-na-big-data-day/"},
            {"title": "Marketing and PR feature", "outlet": "Spot.uz, 06.12.2022",
             "href": "https://www.spot.uz/ru/2022/12/06/marketing-pr/"},
            {"title": "Yandex conference in Uzbekistan: announcement with programme and speakers",
             "outlet": "Spot.uz, 01.12.2022", "href": "https://www.spot.uz/ru/2022/12/01/yandeks-ad/"},
            {"title": "Wunder’s rebranding: how it happened, in the words of the Kazakhstan and "
                      "Uzbekistan CEOs", "outlet": "Tribune.kz",
             "href": "https://tribune.kz/rebrending-wunder-kak-eto-proishodilo-i-chto-ob-etom-dumayut-ceo-ofisov-v-kazahstane-i-uzbekistane/"},
        ],
        "pages": [
            {"title": "Brand Awards International 2026 — award website",
             "outlet": "Marketing Association of Uzbekistan, 2026", "href": "https://bai26.marketing.uz/"},
            {"title": "Board of the Marketing Association of Uzbekistan",
             "outlet": "Marketing Association of Uzbekistan", "href": "https://marketing.uz/about/board/"},
            {"title": "Meet the curators of Tashkent Marketing Forum 2026",
             "outlet": "Marketing Association of Uzbekistan, 2026",
             "href": "https://marketing.uz/news/association/-znakomtes-s-kuratorami-tashkent-marketing-forum-2026.htm"},
            {"title": "Tashkent Marketing Forum 2025 — forum website",
             "outlet": "Marketing Association of Uzbekistan, 2025", "href": "https://tmf25.marketing.uz/"},
            {"title": "TAF!25 international advertising conference: a new level for your business",
             "outlet": "Marketing Association of Uzbekistan, 2025",
             "href": "https://marketing.uz/news/association/mezhdunarodnaya-reklamnaya-konferentsiya-taf25-vozmozhnost-vyjti-na-novyj-uroven-v-reklame-vashego-biznesa.htm"},
            {"title": "Digital communications track speakers at TAF!25",
             "outlet": "Marketing Association of Uzbekistan, 2025",
             "href": "https://marketing.uz/news/association/predstavlyaem-spikerov-sektsii-digital-communications-na-tashkentskom-mezhdunarodnom-festivale-reklamy-taf25.htm"},
            {"title": "TAF! 2024 competition — website", "outlet": "Marketing Association of Uzbekistan, 2024",
             "href": "https://tafkonkurs-2024.marketing.uz/"},
            {"title": "Yandex Ad Conference in Tashkent, 9 December — announcement",
             "outlet": "Facebook, Wunder Digital UZ, 2022",
             "href": "https://www.facebook.com/WunderDigitalUZ/posts/2724650761004617/"},
            {"title": "Yandex Ads Conference Uzbekistan — official event page", "outlet": "Yandex, 2022",
             "href": "https://yandex.ru/promo/events/yaconfuz"},
            {"title": "New board of the Marketing Association of Uzbekistan met on 9 July",
             "outlet": "Marketing Association of Uzbekistan",
             "href": "https://marketing.uz/news/association/9-iyulya-sostoyalos-zasedanie-pravleniya-marketingovoj-assotsiatsii-uzbekistana-v-novom-sostave-.htm"},
            {"title": "Tashkent Digital Marketing Forum — forum page",
             "outlet": "Marketing Association of Uzbekistan", "href": "https://marketing.uz/digital-forum/"},
            {"title": "Retail marketing: joining sales and awareness in one strategy",
             "outlet": "Marketing Association of Uzbekistan",
             "href": "https://marketing.uz/news/association/ritejl-marketing-kak-soedinit-prodazhi-i-uznavaemost-v-odnoj-strategii.htm"},
            {"title": "Uzbekistan to name its Digital Innovator of the Year",
             "outlet": "Marketing Association of Uzbekistan",
             "href": "https://marketing.uz/news/partners/v-uzbekistane-vyberut-digital-innovatora-goda.htm"},
        ],
        "quotes": [],
    },

    "uz": {
        "htmlLang": "uz",
        "ogLocale": "uz_UZ",
        "title": "Igor Kim — Toshkentda digital marketing va internet reklama | Wunder Digital CEO",
        "description": "Igor Kim, Toshkent — Wunder Digital Uzbekistan bosh direktori va Marketing assotsiatsiyasi digital qo‘mitasi raisi. Savdo va marketingda 19 yil, shundan 13 yili internet reklama va analitikada.",
        "kicker": "Digital-ekspert va internet reklama, Toshkent",
        "name": "Igor Kim",
        "jobTitle": "Wunder Digital Uzbekistan bosh direktori",
        "lede": "Digital marketingda 13 yil, 2019-yildan Wunder Digital Uzbekistan’ni "
                "boshqaraman. Marketingning digital va AI transformatsiyasi bilan "
                "shug‘ullanaman, Samsung, Beeline, Pepsi bilan ishlayman. Quyida — "
                "xronologiya, har bir yozuvda manbaga havola bor.",
        "photoAlt": "Igor Kim, Toshkent — Wunder Digital Uzbekistan bosh direktori, internet reklama eksperti",
        "photoSlot": "Surat: marketing.uz",
        "skipLink": "Kontentga o‘tish",
        "langLabel": "Sahifa tili",
        "statuses": [
            "Wunder Digital Uzbekistan bosh direktori",
            "O‘zbekiston Marketing assotsiatsiyasi boshqaruvi a’zosi",
            "O‘zbekiston Marketing assotsiatsiyasi digital qo‘mitasi raisi",
            "Fokus: marketingning digital va AI transformatsiyasi",
        ],
        "trackTitle": "Lavozimlar va statuslar",
        "track": [
            {"label": "Wunder Digital Uzbekistan bosh direktori", "from": 2019, "key": True},
            {"label": "Yandex sertifikatlangan agentligi", "from": 2020},
            {"label": "Google Premier Partner", "from": 2023},
            {"label": "MAU boshqaruvi a’zosi", "from": 2024},
            {"label": "MAU digital qo‘mitasi raisi", "from": 2024, "key": True},
            {"label": "Yandex Direct Gold Partner", "from": 2024, "key": True},
            {"label": "Meta Managed Partner", "from": 2025},
            {"label": "Meta Science Partner", "from": 2026, "key": True},
        ],
        "workTitle": "Ish jarayonida",
        "work": [
            "Soha konferensiyasi, Toshkent",
            "Yandex Ads Conference Uzbekistan",
            "Yandex Ads Conference Uzbekistan, sahnadagi ishtirokchilar",
        ],
        "teamTitle": "Jamoa",
        "team": [
            "Wunder Digital jamoasi, Samarqand",
            "Toshkentdagi ofis",
            "Jamoaning sayohat uchrashuvi",
        ],
        "timelineTitle": "Xronologiya",
        "eraSales": "savdo va distributsiya",
        "eraDigital": "digital",
        "milestones": [
            {"year": 2007, "text": "Reklama biznesidagi birinchi tajriba"},
            {"year": 2011, "text": "WordPress’dagi birinchi sayt, Google reklama va analitika sertifikati"},
            {"year": 2018, "text": "Toshkentda Wunder Digital ofisini ochdi"},
            {"year": 2020, "text": "Yandex sertifikatlangan agentligi", "co": True},
            {"year": 2023, "text": "Google Premier Partner", "co": True},
            {"year": 2025, "text": "O‘zbekiston top-35 marketologi"},
            {"year": 2024, "text": "MAU boshqaruvi a’zosi"},
            {"year": 2024, "text": "MAU digital qo‘mitasi raisi"},
            {"year": 2024, "text": "Yandex Direct Gold Partner", "co": True},
        ],
        "trainingTitle": "O‘qish va sertifikatlar",
        "trainingNote": "kurs",
        "trainingHint": "shu yildagi kurslar",
        "careerTitle": "Ish tajribasi",
        "careerNote": "19 yil, shundan 13 yili digital sohada",
        "jobs": [
            {"role": "CEO", "when": "2018-yil sentabr — hozirgi vaqtda",
             "note": "Wunder Digital’ning O‘zbekistondagi ofisini noldan ochdi: ro‘yxatdan o‘tkazish, "
                     "jamoa, tijorat strategiyasi, savdo kanallari. 2020-yilda agentlik "
                     "kontekst reklama va SEO bo‘yicha mamlakatda №1 deb tan olindi."},
            {"role": "Savdo va marketing direktori", "when": "2017-yil iyun — 2018-yil sentabr",
             "note": "Ommaviy Wi-Fi tarmoqlarini monetizatsiya qilish. Loyihani g‘oyadan "
                     "daromadgacha olib bordi, milliy operator oldida texnik-iqtisodiy asosni "
                     "himoya qildi, Toshkent bo‘ylab 40 ta hamkor jalb qildi."},
            {"role": "Korporativ savdo menejeri", "when": "2011-yil iyun — 2018-yil iyul",
             "note": "Digital yo‘li shu yerdan boshlangan: veb-dasturlash, Google reklamasi va analitikani "
                     "o‘rgandi — kompaniya saytini yasadi va reklamani o‘zi sozladi. Savdo tarmog‘ini "
                     "noldan qurdi, to‘rt yildagi eng yaxshi natijalar."},
            {"role": "Loyihalar menejeri", "when": "2010-yil oktabr — 2014-yil avgust",
             "note": "Xitoy zavodlaridan sanoat uskunalari: pivo liniyalari, press uskunalari, "
                     "qurilish materiallari."},
            {"role": "Korporativ bo‘lim menejeri", "when": "2010-yil mart — sentabr",
             "note": "WiMAX texnologiyasidagi internet-provayder, korporativ segment."},
            {"role": "Savdo bo‘limi boshlig‘i", "when": "2009-yil noyabr — 2010-yil mart",
             "note": "Ostonadagi yangi yo‘nalish: kompyuter uskunalari va videokuzatuv "
                     "tizimlari, jamoa yig‘ish."},
            {"role": "Savdo menejeri", "when": "2009-yil mart — sentabr",
             "note": "Kompyuter va periferiya uskunalari, Xerox va Kyocera, Yekaterinburg."},
            {"role": "Savdo menejeri", "when": "2008-yil avgust — 2009-yil aprel",
             "note": "MDH bo‘ylab AT va telekommunikatsiya distributsiyasi."},
            {"role": "Biznesni rivojlantirish menejeri", "when": "2007-yil iyul — 2008-yil iyun",
             "note": "Birinchi ish va reklama bozori bilan tanishuv — u bu bozorga o‘n yil "
                     "o‘tib qaytadi. IBM Innovation Day forumi, Vogue Arome brendi ishga "
                     "tushirilishi, UNICEF buyurtmasidagi emlash dasturi."},
        ],
        "personTitle": "Qisqacha",
        "person": [
            {"k": "Tug‘ilgan", "v": "1983-yil 24-sentabr"},
            {"k": "Yashaydi", "v": "Toshkent, O‘zbekiston"},
            {"k": "Ta’lim", "v": "Toshkent axborot texnologiyalari universiteti, "
                                 "telekommunikatsiya, bakalavr"},
            {"k": "Tillar", "v": "rus tili — ona tili, ingliz tili — C1"},
            {"k": "Qiziqishlar", "v": "digital, veb-prodakshn, AI, fotografiya va video"},
        ],
        "aboutTitle": "Men haqimda",
        "rolesTitle": "Lavozimlar",
        "awardsTitle": "Yutuqlar",
        "talksTitle": "Ma’ruzalar",
        "juryTitle": "Hakamlar hay’ati",
        "skillsTitle": "Vositalar va platformalar",
        "mediaTitle": "Mediada",
        "pagesTitle": "Rasmiy sahifalar va e’lonlar",
        "navCareer": "Tajriba",
        "navTraining": "O‘qish",
        "trainingPageTitle": "O‘qish, kurslar va sertifikatlar",
        "allTraining": "Barcha kurs va sertifikatlar", "navSpeaking": "Ma’ruzalar",
        "navJury": "Hakamlik", "navMedia": "Media",
        "careerPageTitle": "Ish tajribasi va lavozimlar",
        "speakingPageTitle": "Forum va konferensiyalardagi ma’ruzalar",
        "juryPageTitle": "Professional tanlovlarda hakamlik",
        "allCareer": "To‘liq ish tajribasi", "allSpeaking": "Barcha ma’ruzalar",
        "allJury": "Barcha hakamlik",
        "statusOn": "aloqadaman", "statusOff": "aloqada emasman",
        "statusLeft": "yana", "statusBack": "qaytaman:",
        "units": "kun|soat|daq", "workHours": "Du–Ju, 9:00–18:00, Toshkent",
        "mediaAll": "Mediadagi barcha eslatmalar",
        "mediaPageTitle": "Maqolalar, izohlar va rasmiy sahifalar",
        "backHome": "Bosh sahifaga",
        "quotesTitle": "Fikrlar",
        "contactKicker": "Aloqa",
        "contactTitle": "Ma’ruza, ekspertiza, intervyu",
        "phoneLabel": "Telefon",
        "emailWorkLabel": "Ish pochtasi",
        "agencyLabel": "Agentlik",
        "emailLabel": "Pochta",
        "place": "Toshkent, O‘zbekiston",
        "unitEvents": "tadbir", "unitJury": "tanlov",
        "unitMedia": "material", "unitPages": "havola",
        "about": [
            "Wunder Digital Uzbekistan bosh direktori, digital marketing bo‘yicha ekspert. Sohada "
            "13 yildan ortiq tajriba: reklama investitsiyalari samaradorligi, performance-marketing "
            "va zamonaviy digital yechimlarni joriy etish.",
            "Wunder Digital O‘zbekiston ofisini tashkil etilgan kunidan boshqaradi va kompaniyaning "
            "mahalliy bozordagi strategik rivojlanishi uchun javob beradi. Wunder Digitalga qadar "
            "yirik xalqaro kompaniyalarda rahbarlik lavozimlarida ishlab, digital promoushn uchun "
            "javob bergan. Bozorning eng yirik reklama beruvchilari bilan ishlaydi: Samsung, "
            "Beeline, Pepsi va boshqalar.",
            "O‘zbekistonning top-35 marketologi ro‘yxatida; O‘zbekiston Marketing assotsiatsiyasi "
            "digital qo‘mitasi vakili; digital transformatsiya, analitika va reklama bozori kelajagi "
            "bo‘yicha forumlarda ma’ruza qiladi, professional tanlovlarda hakam bo‘lib ishlaydi.",
        ],
        "proof": "manba",
        "roles": [
            {"title": "CEO", "org": "Wunder Digital O‘zbekiston", "period": "2019-yildan",
             "href": "https://marketing.uz/about/board/kim-igor.htm"},
            {"title": "Digital qo‘mita raisi", "org": "O‘zbekiston Marketing assotsiatsiyasi",
             "period": "2024-yil iyulidan",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
            {"title": "O‘zbekiston top-35 marketologi", "org": "O‘zbekiston Marketing assotsiatsiyasi",
             "period": "2025-yil yakunlari",
             "href": "https://marketing.uz/news/association/top35-marketologov-uzbekistana-po-itogam-2025-goda.htm"},
            {"title": "Boshqaruv a’zosi", "org": "O‘zbekiston Marketing assotsiatsiyasi",
             "period": "hozirgi vaqtda", "href": "https://marketing.uz/about/board/kim-igor.htm"},
            {"title": "Assotsiatsiya eksperti", "org": "O‘zbekiston Marketing assotsiatsiyasi",
             "period": "hozirgi vaqtda",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
        ],
        "awards": [
            {"year": "2025", "title": "O‘zbekiston top-35 marketologi",
             "desc": "Yil yakunlari bo‘yicha mamlakatning yetakchi marketologlari ro‘yxatida.",
             "href": "https://marketing.uz/news/association/top35-marketologov-uzbekistana-po-itogam-2025-goda.htm"},
            {"year": "2024-yildan", "title": "Digital qo‘mita raisi",
             "desc": "O‘zbekiston Marketing assotsiatsiyasi.",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
            {"year": "2024-yildan", "title": "Boshqaruv a’zosi",
             "desc": "O‘zbekiston Marketing assotsiatsiyasi.",
             "href": "https://marketing.uz/about/board/"},
            {"year": "—", "title": "Assotsiatsiya eksperti",
             "desc": "O‘zbekiston Marketing assotsiatsiyasi.",
             "href": "https://marketing.uz/experts/marketing-association/kim-igor.htm"},
        ],
        "agencyTitle": "Agentlik yutuqlari",
        "agencyNote": "u boshqaradigan Wunder Digital Uzbekistan",
        "talks": [
            {"event": "Tashkent Advertising Festival TAF!26", "sub": "Konferensiya ma’ruzachisi",
             "meta": "Toshkent, Hyatt Regency, 2026", "href": "https://taf26.marketing.uz/speakers/24.htm"},
            {"event": "Tashkent Marketing Forum 2026", "sub": "Digital seksiya kuratori",
             "meta": "Toshkent, 2026-yil 14-fevral",
             "href": "https://tmf26.marketing.uz/forum-curators/igor-kim.htm"},
            {"event": "Tashkent Marketing Forum 2025", "sub": "Digital Marketing seksiyasi",
             "meta": "Toshkent, 2025",
             "href": "https://marketing.uz/news/association/cpikers-sektsii-digital-marketing-na-tashkent-marketing-forum-2025.htm"},
            {"event": "Tashkent Advertising Festival TAF!25",
             "sub": "Digital communications seksiyasi ma’ruzachisi",
             "meta": "Toshkent, 2025-yil 11–12-oktabr", "href": "https://uznews.uz/ru/news/103608"},
            {"event": "Yandex Ads Conference Uzbekistan",
             "sub": "«Biznesga medijnaya reklama nima uchun kerak va uni qanday natijali qilish mumkin»",
             "meta": "Toshkent, Hilton Tashkent City, 2024-yil 14-may",
             "href": "https://yandex.ru/adv/project/yaconfuzb2024"},
            {"event": "Tashkent Digital Marketing Forum 2023", "sub": "Forum kuratori",
             "meta": "Toshkent, 2023",
             "href": "https://marketing.uz/digital-forum/kuratory-foruma/igor-kim.htm"},
            {"event": "Big Data Day, Wunder Digital",
             "sub": "«Quruvchining savdosini 66%ga oshirish: O‘zbekistonda mobil operator Big Data’si "
                    "bilan birinchi keys»",
             "meta": "2023-yil 27-aprel", "href": "https://tribune.kz/wunder-digital-agency-provedet-big-data-day/"},
            {"event": "Ko‘chmas mulk marketingi bo‘yicha vebinar (QZ — UZ — BY)",
             "sub": "«Quruvchining savdosini 66%ga oshirish: O‘zbekistonda mobil operator Big Data’si "
                    "bilan birinchi keys»",
             "meta": "2023-yil 30-may",
             "href": "https://dknews.kz/ru/biznes/290580-uspeshnaya-prodazha-nedvizhimosti-v-kazahstane-sovety"},
            {"event": "O‘zbekistonda Yandex konferensiyasi", "sub": "Ma’ruzachi",
             "meta": "Toshkent, 2022-yil 9-dekabr", "href": "https://www.gazeta.uz/ru/2022/12/01/yandeks-ad/"},
        ],
        "jury": [
            {"event": "Brand Awards International 2026", "sub": "Hakamlar hay’ati a’zosi", "meta": "2026",
             "href": "https://bai26.marketing.uz/en/judges/igor-kim.htm"},
            {"event": "Toshkent reklama festivali TAF! tanlovi", "sub": "Hakamlar hay’ati a’zosi",
             "meta": "2024", "href": "https://tafkonkurs-2024.marketing.uz/judges/kim-igor.htm"},
            {"event": "Toshkent reklama festivali TAF! tanlovi", "sub": "Tanlov eksperti", "meta": "2023",
             "href": "https://marketing.uz/tafexpert-konkurs-2023"},
            {"event": "ePlus Award", "sub": "Hakamlar hay’ati a’zosi", "meta": "2024",
             "href": "https://car.eplus.marketing/car/award/jury/jury-old/2024"},
            {"event": "ePlus Award", "sub": "Hakamlar hay’ati a’zosi", "meta": "2023",
             "href": "https://car.eplus.marketing/car/award/jury/jury-old/2023/"},
            {"event": "Yilning brendi", "sub": "Hakamlar hay’ati a’zosi", "meta": "2023",
             "href": "https://brendgoda-2023.marketing.uz/judges/kim-igor.htm"},
            {"event": "Yilning brendi", "sub": "Hakamlar hay’ati a’zosi", "meta": "2022",
             "href": "https://marketing.uz/brend-goda-2022/jury/kim-igor.htm"},
        ],
        "skills": [
            {"group": "Reklama va sotib olish",
             "items": "Google Ads · Yandex Ads · Meta Ads · DV360 · Telegram Ads"},
            {"group": "Analitika", "items": "Google Analytics · Yandex Metrica · AppMetrica"},
            {"group": "Mobil atributsiya", "items": "Adjust · AppsFlyer"},
            {"group": "Veb-prodakshn", "items": "WordPress · Tilda"},
        ],
        "media": [
            {"title": "Marketing — biznes o‘sishining drayveri: Tashkent Marketing Forum 2026 "
                      "nimalarni muhokama qiladi", "outlet": "PR.uz, 04.02.2026",
             "href": "https://pr.uz/marketing-kak-drajver-rosta/"},
            {"title": "To‘rtinchi xalqaro Tashkent Marketing Forum 2026 qanday o‘tdi",
             "outlet": "WeProject Media, 2026",
             "href": "https://weproject.media/articles/detail/kak-proshel-chetvertyy-mezhdunarodnyy-tashkent-marketing-forum-2026/"},
            {"title": "Marketing biznesni qanday o‘stirishi kerak va 2026-yilda buni kim ko‘rsatadi",
             "outlet": "Gazeta.uz, 04.02.2026", "href": "https://www.gazeta.uz/ru/2026/02/04/marketing-forum-2026/"},
            {"title": "Marketing biznesni qanday o‘stirishi kerak va 2026-yilda buni kim ko‘rsatadi",
             "outlet": "Nuz.uz, 27.01.2026",
             "href": "https://nuz.uz/2026/01/27/kak-marketing-dolzhen-razvivat-biznes-i-kto-pokazhet-kak-eto-delat-v-2026-godu/"},
            {"title": "Marketing biznesni qanday o‘stirishi kerak — 2026-yilda buni kim ko‘rsatadi",
             "outlet": "Vzglyad.uz, 23.01.2026",
             "href": "https://vzglyad.uz/2026/01/23/kak-marketing-dolzhen-razvivat-biznes-i-kto-pokazhet-kak-eto-delat-v-2026-godu/"},
            {"title": "Nashr eksperti va kolumnisti profili", "outlet": "Kursiv Media O‘zbekiston",
             "href": "https://uz.kursiv.media/expert/igor-kim/"},
            {"title": "Ekrandan xaridorgacha: DOOH nima va do‘konga kelishni qanday kuzatadi — "
                      "muallif ustuni", "outlet": "Kursiv Media O‘zbekiston, 21.07.2025",
             "href": "https://uz.kursiv.media/opinions/ot-ekrana-k-pokupatelyu-chto-takoe-czifrovaya-naruzhnaya-reklama-i-kak-ona-pomogaet-otslezhivat-dohodimost-do-tochek-prodazh/"},
            {"title": "Yettinchi Toshkent xalqaro reklama festivali TAF!25 g‘oliblarini e’lon qildi",
             "outlet": "Nova24.uz, 2025",
             "href": "https://nova24.uz/uzbekistan/sedmoj-tashkentskij-mezhdunarodnyj-festival-reklamy-taf-25-obyavil-pobeditelej-i-podvel-itogi/"},
            {"title": "TAF!25 xalqaro reklama konferensiyasi: biznesingiz reklamasida yangi daraja",
             "outlet": "Frank.uz, 2025",
             "href": "https://frank.uz/news/mezhdunarodnaya-reklamnaya-konferencziya-taf25-vozmozhnost-vyjti-na-novyj-uroven-v-reklame-vashego-biznesa/"},
            {"title": "O‘zbekistonda digital marketing: 2025 tendensiyalari. Ekspert izohi",
             "outlet": "Astana Hub, 2025",
             "href": "https://astanahub.com/en/blog/didzhital-marketing-v-uzbekistane-tendentsii-2025-goda1759934363"},
            {"title": "O‘zbekistonda digital marketing: 2025-yilning asosiy tendensiyalari. Ekspert izohi",
             "outlet": "Sostav.ru, 08.10.2025", "href": "https://www.sostav.ru/blogs/141843/68775"},
            {"title": "O‘zbekistonda digital marketing — 2025 tendensiyalari. Ekspert izohi",
             "outlet": "BYYD, 07.10.2025",
             "href": "https://www.byyd.me/ru/blog/2025/10/digital-marketing-in-uzbekistan-trends-for-2025/"},
            {"title": "E+ Awards Markaziy Osiyo 2024 hakamlar hay’ati shakllantirildi",
             "outlet": "Tribune.kz, 2024",
             "href": "https://tribune.kz/zavershilos-formirovanie-sudejskogo-korpusa-e-awards-tsentralnaya-aziya-2024/"},
            {"title": "Ko‘chmas mulkni qanday sotish kerak? Wunder Digital vebinari",
             "outlet": "Spot.uz, 25.05.2023", "href": "https://www.spot.uz/ru/2023/05/25/wunder-digital/"},
            {"title": "Ko‘chmas mulkni qanday sotish kerak? Wunder Digital’ning bepul vebinari",
             "outlet": "Goodstart.by, 2023",
             "href": "https://goodstart.by/new/wunder-digital-webinar-promotion-realty-2023"},
            {"title": "Ko‘chmas mulkni qanday sotish kerak? Wunder Digital’ning bepul vebinari",
             "outlet": "Domovita.by, 2023",
             "href": "https://domovita.by/news/kak-prodvigat-nedvizimost-ctoby-ee-pokupali-besplatnyj-vebinar-ot-wunder-digital"},
            {"title": "Ko‘chmas mulkni qanday sotish kerak? Wunder Digital’ning bepul vebinari",
             "outlet": "Homsters.kz, 2023",
             "href": "https://info.homsters.kz/kak-prodvigat-nedvizhimost-chtoby-ee-pokupali-besplatnyj-vebinar-ot-wunder-digital/"},
            {"title": "Ko‘chmas mulkni qanday sotish kerak? Wunder Digital vebinari dasturi",
             "outlet": "Ekonomicheskaya Gazeta (neg.by), 31.05.2023",
             "href": "https://neg.by/novosti/otkrytj/kak-prodvigat-nedvizhimost-chtoby-ee-pokupali-besplatnyy-vebinar-ot-wunder-digital/"},
            {"title": "O‘zbekistonda birinchi Tashkent Digital Marketing Forum boshlandi",
             "outlet": "PC.uz, 2023", "href": "https://pc.uz/news/152339-v-uzbekistane-startoval-pervyj"},
            {"title": "Toshkentda birinchi xalqaro Tashkent Digital Marketing Forum 2023 bo‘lib o‘tdi",
             "outlet": "UzDaily, 2023",
             "href": "https://www.uzdaily.uz/ru/v-tashkente-proshel-pervyi-mezhdunarodnyi-tashkent-digital-marketing-forum-2023/"},
            {"title": "2023-yilda O‘zbekistonda dori vositalari reklamasidagi 3 tendensiya",
             "outlet": "Wunder Digital, 2023",
             "href": "https://wunder-digital.uz/3-trenda-v-reklame-lekarstvennyh-sredstv-v-2023-godu-v-uzbekistane/"},
            {"title": "Wunder Digital Agency Big Data Day’ga taklif qiladi — dastur",
             "outlet": "Edu-afisha, 2023",
             "href": "https://edu-afisha.ru/event/wunder-digital-agency-priglashaet-na-big-data-day/"},
            {"title": "Marketing va PR haqida material", "outlet": "Spot.uz, 06.12.2022",
             "href": "https://www.spot.uz/ru/2022/12/06/marketing-pr/"},
            {"title": "O‘zbekistonda Yandex konferensiyasi: dastur va ma’ruzachilar",
             "outlet": "Spot.uz, 01.12.2022", "href": "https://www.spot.uz/ru/2022/12/01/yandeks-ad/"},
            {"title": "Wunder rebrendingi: Qozog‘iston va O‘zbekiston ofislari CEO’lari fikri",
             "outlet": "Tribune.kz",
             "href": "https://tribune.kz/rebrending-wunder-kak-eto-proishodilo-i-chto-ob-etom-dumayut-ceo-ofisov-v-kazahstane-i-uzbekistane/"},
        ],
        "pages": [
            {"title": "Brand Awards International 2026 — mukofot sayti",
             "outlet": "O‘zbekiston Marketing assotsiatsiyasi, 2026", "href": "https://bai26.marketing.uz/"},
            {"title": "O‘zbekiston Marketing assotsiatsiyasi boshqaruvi tarkibi",
             "outlet": "O‘zbekiston Marketing assotsiatsiyasi", "href": "https://marketing.uz/about/board/"},
            {"title": "Tashkent Marketing Forum 2026 kuratorlari bilan tanishing",
             "outlet": "O‘zbekiston Marketing assotsiatsiyasi, 2026",
             "href": "https://marketing.uz/news/association/-znakomtes-s-kuratorami-tashkent-marketing-forum-2026.htm"},
            {"title": "Tashkent Marketing Forum 2025 — forum sayti",
             "outlet": "O‘zbekiston Marketing assotsiatsiyasi, 2025", "href": "https://tmf25.marketing.uz/"},
            {"title": "TAF!25 xalqaro reklama konferensiyasi: biznesingiz reklamasida yangi daraja",
             "outlet": "O‘zbekiston Marketing assotsiatsiyasi, 2025",
             "href": "https://marketing.uz/news/association/mezhdunarodnaya-reklamnaya-konferentsiya-taf25-vozmozhnost-vyjti-na-novyj-uroven-v-reklame-vashego-biznesa.htm"},
            {"title": "TAF!25 Digital communications seksiyasi ma’ruzachilari",
             "outlet": "O‘zbekiston Marketing assotsiatsiyasi, 2025",
             "href": "https://marketing.uz/news/association/predstavlyaem-spikerov-sektsii-digital-communications-na-tashkentskom-mezhdunarodnom-festivale-reklamy-taf25.htm"},
            {"title": "TAF! 2024 tanlovi — sayt", "outlet": "O‘zbekiston Marketing assotsiatsiyasi, 2024",
             "href": "https://tafkonkurs-2024.marketing.uz/"},
            {"title": "Toshkentda Yandex Ad Conference, 9-dekabr — e’lon",
             "outlet": "Facebook, Wunder Digital UZ, 2022",
             "href": "https://www.facebook.com/WunderDigitalUZ/posts/2724650761004617/"},
            {"title": "Yandex Ads Conference Uzbekistan — tadbirning rasmiy sahifasi",
             "outlet": "Yandex, 2022", "href": "https://yandex.ru/promo/events/yaconfuz"},
            {"title": "9-iyulda O‘zbekiston Marketing assotsiatsiyasi boshqaruvining yangi tarkibdagi "
                      "yig‘ilishi", "outlet": "O‘zbekiston Marketing assotsiatsiyasi",
             "href": "https://marketing.uz/news/association/9-iyulya-sostoyalos-zasedanie-pravleniya-marketingovoj-assotsiatsii-uzbekistana-v-novom-sostave-.htm"},
            {"title": "Tashkent Digital Marketing Forum — forum sahifasi",
             "outlet": "O‘zbekiston Marketing assotsiatsiyasi", "href": "https://marketing.uz/digital-forum/"},
            {"title": "Riteyl-marketing: savdo va tanilishni bitta strategiyada birlashtirish",
             "outlet": "O‘zbekiston Marketing assotsiatsiyasi",
             "href": "https://marketing.uz/news/association/ritejl-marketing-kak-soedinit-prodazhi-i-uznavaemost-v-odnoj-strategii.htm"},
            {"title": "O‘zbekistonda yilning Digital innovatori tanlanadi",
             "outlet": "O‘zbekiston Marketing assotsiatsiyasi",
             "href": "https://marketing.uz/news/partners/v-uzbekistane-vyberut-digital-innovatora-goda.htm"},
        ],
        "quotes": [],
    },
}
